'use client';

import { useState } from 'react';
import GeneratingState from '@/components/GeneratingState';
import MessageState from '@/components/MessageState';
import PrimaryButton from '@/components/PrimaryButton';
import LinkButton from '@/components/LinkButton';
import SubmitError from '@/components/SubmitError';
import ConstellationCard from '@/components/ConstellationCard';
import ChipRow from '@/components/ChipRow';
import type { PathReportState } from '@/lib/use-path-report';
import type { ProjectNamingState } from '@/lib/use-project-naming';

// #134 Slice 3 UI — final "Your Path" report + naming, the terminal step of
// the redesigned /path flow. Mirrors components/OptionsFlow.tsx's
// file-per-flow convention and its generating/failed GeneratingState/
// MessageState composition, but path_report's own phase vocabulary comes
// from lib/use-path-report.ts's plain GenerationPhase (Tier C: idle/
// spinner/come-back-later/ready/failed), not the checkpoint-session union
// OptionsFlow branches on — see use-path-report.ts's own header for why.
//
// Report sections originally mirrored the recovered pre-#134 Stage D report
// render (git commit faedc73); 'not_this' and 'plan_seed_actions' were
// dropped from the start, they belonged to the old Stage 5/6 schema and
// have no equivalent here (see this session's own scoping pass).
//
// #139 — full content-design rebuild (docs/briefs/139-path-report-redesign.md).
// thesis/what_it_is/honest_cost/master_strategy are gone; summary/
// what_this_could_be/life_it_leads_toward/strategic_decisions replace them.
// honest_cost's own section is removed entirely (confirmed cut, not an
// oversight — its job is absorbed into life_it_leads_toward's own friction-
// as-trade-off beat). Cover now carries an H1 (chosen_candidate.name) plus
// TWO stacked paragraphs, both styled via .identity-thesis for visual
// consistency with OptionsFlow.tsx's own OPTIONS_INTRO precedent (a full
// paragraph living inside a cover, not a separate card) — the short thesis
// line (chosen_candidate.core_statement, carried through from the Options
// candidate the user picked, never regenerated by this prompt) first, then
// the longer generated summary paragraph. why_it_fits now renders as two
// `<p>`s (a content requirement, not just a render choice) — the prompt
// separates its two paragraphs with a blank line, split here on that same
// literal separator; `.card p + p` supplies the gap between them since the
// global `p { margin: 0 }` reset leaves none by default. Strategic
// Decisions reuses master_strategy's own ConstellationCard-per-item render
// verbatim, just fed different props (decision/why_it_matters/live_options
// instead of name/description/sequencing_rationale) — live_options render
// via ChipRow, reusing OptionsFlow.tsx's own "DRAWS ON" treatment
// (option-card-sigs) rather than inventing new markup, since the brief
// explicitly called this "Claude Code's call" between a chip row and a
// bulleted list and these are meant to read as short phrases, not
// sentences.
//
// Naming is NOT auto-offered on report-ready and NOT offered at Options'
// selection step (both deliberately ruled out this session) — it sits at
// the bottom of the finished report, next to a static "what's next" teaser
// with no real destination yet (/plan still reads the old pre-#134
// path_selections table and is orphaned by this pipeline; /mentor isn't
// finished for this flow either — both out of scope here; /plan's
// reconnection is its own follow-up ticket, not touched this session).
// Naming is the one real, working interaction in that bottom block.
//
// The naming dialog markup is recovered near-verbatim from faedc73's own
// project naming dialog, with one simplification: the old dialog tracked
// selectedName/customName as two separate fields; here a single customName
// covers both (clicking a suggestion just writes its name into the same
// field), since the saved value only ever needs to be "whichever string is
// in the box" either way.

const GENERATING_HEADING = 'Your Path is being finalized.';
const GENERATING_EARLY_COPY = 'This usually takes about a minute.';
const GENERATING_LATE_COPY = 'Still working — this is taking a little longer than usual…';
const COME_BACK_LATER_COPY =
  'Your Path is still being finalized. This is taking longer than expected — you can leave this page and come ' +
  'back in a few minutes. It’ll be here when it’s ready.';
const FAILED_BODY = 'We couldn’t finish your Path report. Please try again.';

const WHAT_THIS_COULD_BE_EXPLANATION =
  'Not the day-to-day — that’s above. This is about where this goes: what it grows into, what you become known ' +
  'for, over time.';
const WHY_IT_FITS_EXPLANATION =
  'Two separate things have to be true for a direction to be real: you have to be capable of it, and it has to ' +
  'be something you actually want. This is where both get named, and where they overlap.';
const DESTINATION_EXPLANATION =
  'What actually doing this would look like, concretely, given who you demonstrably are — including the one real ' +
  'trade-off it asks of you. Not a promise of happiness — just an honest picture.';
const STRATEGY_EXPLANATION =
  'Not a plan yet — the real open decisions this direction actually has, and what’s genuinely on the table for ' +
  'each one.';

const WHATS_NEXT_COPY =
  'Next, this turns into a Project — a Plan for walking this path, and concrete actions to start moving. Not ' +
  'built yet, but it’s coming.';

type PathReportFlowProps = {
  report: PathReportState;
  naming: ProjectNamingState;
};

export default function PathReportFlow({ report, naming }: PathReportFlowProps) {
  const [customName, setCustomName] = useState('');

  function handleOpenNaming() {
    setCustomName('');
    naming.openAndGenerate();
  }

  async function handleSave(name: string | null) {
    const saved = await naming.save(name);
    if (saved !== undefined) {
      report.setProjectName(saved);
      setCustomName('');
    }
  }

  // ── Generating / failed / not-yet-ready ──────────────────────────────
  if (report.phase.phase === 'failed') {
    return (
      <MessageState
        eyebrow="YOUR PATH"
        heading="Something went wrong."
        body={FAILED_BODY}
        cta={<PrimaryButton onClick={report.retry}>Try again</PrimaryButton>}
      />
    );
  }

  if (report.phase.phase === 'come-back-later') {
    return <GeneratingState spinner={false} description={COME_BACK_LATER_COPY} />;
  }

  if (report.phase.phase !== 'ready' || !report.content) {
    const description =
      report.phase.phase === 'spinner' && report.phase.variant === 'late' ? GENERATING_LATE_COPY : GENERATING_EARLY_COPY;
    return <GeneratingState heading={GENERATING_HEADING} description={description} />;
  }

  // ── Ready: full report ────────────────────────────────────────────────
  // Narrowed via a local const, same convention app/path/page.tsx's own
  // comments already document — TS can't carry the guard above's narrowing
  // of `report.content` through unrelated intervening reads otherwise.
  const content = report.content;
  const {
    chosen_candidate, summary, what_this_could_be, why_it_fits, life_it_leads_toward, strategic_decisions, project_name,
  } = content;

  // why_it_fits is generated as two paragraphs separated by a blank line
  // (lib/prompts/path-report.ts's own explicit instruction) — split on that
  // literal separator so each renders as its own <p>. Falls back to a
  // single paragraph if a draft somehow didn't include the separator,
  // rather than rendering an empty second <p>.
  const whyItFitsParagraphs = why_it_fits.split(/\n\s*\n/).map(p => p.trim()).filter(Boolean);

  return (
    <>
      {naming.open && (
        <div className="dialog-overlay" role="dialog" aria-modal="true">
          <div className="dialog-card">
            <p className="eyebrow">NAME YOUR PROJECT</p>
            <h2>Want to name this?</h2>
            <p>Give this direction a name of its own, or skip — your Path stays exactly as it is either way.</p>

            {naming.loading && <div className="spin spinner" />}

            {!naming.loading && naming.options.length > 0 && (
              <div className="project-name-options">
                {naming.options.map(opt => (
                  <button
                    key={opt.name}
                    type="button"
                    onClick={() => setCustomName(opt.name)}
                    className={`project-name-card${customName === opt.name ? ' selected' : ''}`}
                  >
                    <div className="project-name-card-title">{opt.name}</div>
                    <p className="project-name-card-rationale">{opt.rationale}</p>
                  </button>
                ))}
              </div>
            )}

            {!naming.loading && (
              <input
                className="input-field"
                type="text"
                placeholder="Or write your own"
                value={customName}
                onChange={(e) => setCustomName(e.target.value)}
              />
            )}

            <SubmitError error={naming.error} />

            <div className="dialog-actions">
              <PrimaryButton
                onClick={() => handleSave(customName.trim() || null)}
                disabled={naming.saving || !customName.trim()}
              >
                {naming.saving ? 'Saving…' : 'Name this Project'}
              </PrimaryButton>
              <LinkButton onClick={() => handleSave(null)} disabled={naming.saving}>
                Skip
              </LinkButton>
            </div>
          </div>
        </div>
      )}

      <div className="flow-container">
        <div className="scroll">

          <div className="section cover">
            <p className="eyebrow">Your Path</p>
            <h1>{chosen_candidate.name}</h1>
            {project_name && <p className="cover-context-line">{project_name}</p>}
            <p className="identity-thesis">{chosen_candidate.core_statement}</p>
            <p className="identity-thesis">{summary}</p>
          </div>

          <div className="section">
            <p className="eyebrow">WHAT THIS COULD BE</p>
            <p className="documentation">{WHAT_THIS_COULD_BE_EXPLANATION}</p>
            <div className="card"><p>{what_this_could_be}</p></div>
          </div>

          <div className="section">
            <p className="eyebrow">WHY IT FITS</p>
            <p className="documentation">{WHY_IT_FITS_EXPLANATION}</p>
            <div className="card">
              {whyItFitsParagraphs.map((paragraph, i) => <p key={i}>{paragraph}</p>)}
            </div>
          </div>

          <div className="section">
            <p className="eyebrow">WHERE THIS LEADS</p>
            <p className="documentation">{DESTINATION_EXPLANATION}</p>
            <div className="card"><p>{life_it_leads_toward}</p></div>
          </div>

          <div className="section">
            <p className="eyebrow">HOW YOU GET THERE</p>
            <p className="documentation">{STRATEGY_EXPLANATION}</p>
            {strategic_decisions.map((sd, i) => (
              <ConstellationCard key={sd.decision} badge={i + 1} title={sd.decision}>
                <p className="evidence-analysis">{sd.why_it_matters}</p>
                <p className="card-sub-label" style={{ margin: '14px 16px 6px' }}>OPEN DIRECTIONS</p>
                <ChipRow items={sd.live_options} wrapperClassName="option-card-sigs" />
              </ConstellationCard>
            ))}
          </div>

          <div className="section">
            <div className="card" style={{ textAlign: 'center' }}>
              <p>{WHATS_NEXT_COPY}</p>
              {project_name ? (
                <>
                  <p>You&rsquo;re calling this <strong>{project_name}</strong>.</p>
                  <LinkButton onClick={handleOpenNaming}>Rename it</LinkButton>
                </>
              ) : (
                <LinkButton onClick={handleOpenNaming}>Name this project</LinkButton>
              )}
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
