'use client';

import { useState } from 'react';
import GeneratingState from '@/components/GeneratingState';
import MessageState from '@/components/MessageState';
import PrimaryButton from '@/components/PrimaryButton';
import LinkButton from '@/components/LinkButton';
import SubmitError from '@/components/SubmitError';
import ConstellationCard from '@/components/ConstellationCard';
import type { PathReportState } from '@/lib/use-path-report';
import type { ProjectNamingState } from '@/lib/use-project-naming';

// #134 Slice 3 UI — final "Your Path" report + naming, the terminal step of
// the redesigned /path flow. Mirrors components/OptionsFlow.tsx's
// file-per-flow convention and its generating/failed GeneratingState/
// MessageState composition, but path_report's own phase vocabulary comes
// from lib/use-path-report.ts's plain GenerationPhase (Tier C: idle/
// spinner/come-back-later/ready/failed), not the checkpoint-session union
// OptionsFlow branches on — see use-path-report.ts's own header for why.
//
// Report sections originally mirrored the recovered pre-#134 Stage D report
// render (git commit faedc73); 'not_this' and 'plan_seed_actions' were
// dropped from the start, they belonged to the old Stage 5/6 schema and
// have no equivalent here (see this session's own scoping pass).
//
// #139 — full content-design rebuild (docs/briefs/139-path-report-redesign.md).
// thesis/what_it_is/honest_cost/master_strategy are gone; summary/
// what_this_could_be/life_it_leads_toward/strategic_decisions replace them.
// honest_cost's own section is removed entirely (confirmed cut, not an
// oversight — its job is absorbed into life_it_leads_toward's own friction-
// as-trade-off beat). Cover carries an H1 (chosen_candidate.name), then the
// short thesis line (chosen_candidate.core_statement, carried through from
// the Options candidate the user picked, never regenerated by this prompt)
// styled via .identity-thesis, then the longer generated summary paragraph
// as a plain <p> (see #144 below — the original #139 design wrongly reused
// .identity-thesis for the summary too, which made it read as "too long"
// purely from the styling). why_it_fits is still generated as a single
// string, its two paragraphs separated by a blank line (schema unchanged,
// #144 confirmed a render-only fix is cleaner here) — split on that same
// literal separator, one paragraph per real card with its own `<h3>`
// (#144: was one card with two stacked `<p>`s). Strategic
// Decisions reuses master_strategy's own ConstellationCard-per-item render
// verbatim, just fed different props (decision/why_it_matters/live_options
// instead of name/description/sequencing_rationale).
//
// #144 (docs/briefs/144-path-report-live-review-fixes.md, post-#139 live
// review): live_options was originally rendered via ChipRow — "only pills
// are pretty but useless" — replaced with a real schema change
// (LiveOption { option; context }, lib/generate-path-report.ts) and a
// labeled-sub-section render: each option is its own `card-sub-label` +
// `evidence-analysis` pair (both reused verbatim from elsewhere in this
// same card, margins overridden inline the same way "OPEN DIRECTIONS"
// already does — no new CSS classes needed), giving each option enough
// space to actually explain the direction instead of just naming it.
// why_it_matters' own paragraph dropped .evidence-analysis too (kept the
// same padding inline, just not the muted/small citation-style font
// treatment — that class was inherited from the old master_strategy render
// and was never right for this section's primary content). Cover gained a
// real cover-context-line (`{prepared_for} · {identity_context}`, same
// pattern as /identity's own cover — attached by the route from
// identityReport.cover, not generated).
//
// Naming is NOT auto-offered on report-ready and NOT offered at Options'
// selection step (both deliberately ruled out this session) — it sits at
// the bottom of the finished report, next to a static "what's next" teaser
// with no real destination yet (/plan still reads the old pre-#134
// path_selections table and is orphaned by this pipeline; /mentor isn't
// finished for this flow either — both out of scope here; /plan's
// reconnection is its own follow-up ticket, not touched this session).
// Naming is the one real, working interaction in that bottom block.
//
// The naming dialog markup is recovered near-verbatim from faedc73's own
// project naming dialog, with one simplification: the old dialog tracked
// selectedName/customName as two separate fields; here a single customName
// covers both (clicking a suggestion just writes its name into the same
// field), since the saved value only ever needs to be "whichever string is
// in the box" either way.
//
// #144: the bottom "what's next" block's wrapper was a plain .card with
// inline textAlign, never actually using this project's real .section.cta/
// .card.cta styling system (components/ReframeCtaBlock.tsx is the working
// reference, used on /identity) — replaced verbatim, render-only, per the
// brief's explicit "reuse existing formatting, don't invent new ones."
// Naming dialog/pitch content itself is unchanged, only the wrapper.

const GENERATING_HEADING = 'Your Path is being finalized.';
const GENERATING_EARLY_COPY = 'This usually takes about a minute.';
const GENERATING_LATE_COPY = 'Still working. This is taking a little longer than usual…';
const COME_BACK_LATER_COPY =
  'Your Path is still being finalized. This is taking longer than expected. You can leave this page and come ' +
  'back in a few minutes. It’ll be here when it’s ready.';
const FAILED_BODY = 'We couldn’t finish your Path report. Please try again.';

// #144: help text rewritten throughout — no em dashes anywhere (global
// rule, docs/briefs/144-path-report-live-review-fixes.md), and What This
// Could Be's specifically reworked to set the expectation of one confident
// vision directly, not just describe scope (the old copy read as
// "uninspiring" per live review).
const WHAT_THIS_COULD_BE_EXPLANATION =
  'One real, confident picture of where this leads if you follow it all the way. Not a list of maybes.';
const WHY_IT_FITS_EXPLANATION =
  'Two things have to be true for a direction to be real. You have to be capable of it, and you have to actually ' +
  'want it. Both get named here, and where they meet.';
const DESTINATION_EXPLANATION =
  'What a real day actually doing this looks like, given who you demonstrably are. Includes the one real ' +
  'trade-off it asks of you. Not a promise of happiness, just an honest picture.';
const STRATEGY_EXPLANATION =
  'Not a plan yet. The real open decisions this direction actually has, and what’s genuinely on the table for ' +
  'each one.';

const WHATS_NEXT_COPY =
  'Next, this turns into a Project: a Plan for walking this path, and concrete actions to start moving. Not ' +
  'built yet, but it’s coming.';

type PathReportFlowProps = {
  report: PathReportState;
  naming: ProjectNamingState;
};

export default function PathReportFlow({ report, naming }: PathReportFlowProps) {
  const [customName, setCustomName] = useState('');

  function handleOpenNaming() {
    setCustomName('');
    naming.openAndGenerate();
  }

  async function handleSave(name: string | null) {
    const saved = await naming.save(name);
    if (saved !== undefined) {
      report.setProjectName(saved);
      setCustomName('');
    }
  }

  // ── Generating / failed / not-yet-ready ──────────────────────────────
  if (report.phase.phase === 'failed') {
    return (
      <MessageState
        eyebrow="YOUR PATH"
        heading="Something went wrong."
        body={FAILED_BODY}
        cta={<PrimaryButton onClick={report.retry}>Try again</PrimaryButton>}
      />
    );
  }

  if (report.phase.phase === 'come-back-later') {
    return <GeneratingState spinner={false} description={COME_BACK_LATER_COPY} />;
  }

  if (report.phase.phase !== 'ready' || !report.content) {
    const description =
      report.phase.phase === 'spinner' && report.phase.variant === 'late' ? GENERATING_LATE_COPY : GENERATING_EARLY_COPY;
    return <GeneratingState heading={GENERATING_HEADING} description={description} />;
  }

  // ── Ready: full report ────────────────────────────────────────────────
  // Narrowed via a local const, same convention app/path/page.tsx's own
  // comments already document — TS can't carry the guard above's narrowing
  // of `report.content` through unrelated intervening reads otherwise.
  const content = report.content;
  const {
    chosen_candidate, summary, what_this_could_be, why_it_fits, life_it_leads_toward, strategic_decisions,
    prepared_for, identity_context, project_name,
  } = content;

  // why_it_fits is generated as two paragraphs separated by a blank line
  // (lib/prompts/path-report.ts's own explicit instruction) — split on that
  // literal separator so each renders as its own <p>. Falls back to a
  // single paragraph if a draft somehow didn't include the separator,
  // rather than rendering an empty second <p>.
  const whyItFitsParagraphs = why_it_fits.split(/\n\s*\n/).map(p => p.trim()).filter(Boolean);

  return (
    <>
      {naming.open && (
        <div className="dialog-overlay" role="dialog" aria-modal="true">
          <div className="dialog-card">
            <p className="eyebrow">NAME YOUR PROJECT</p>
            <h2>Want to name this?</h2>
            <p>Give this direction a name of its own, or skip. Your Path stays exactly as it is either way.</p>

            {naming.loading && <div className="spin spinner" />}

            {!naming.loading && naming.options.length > 0 && (
              <div className="project-name-options">
                {naming.options.map(opt => (
                  <button
                    key={opt.name}
                    type="button"
                    onClick={() => setCustomName(opt.name)}
                    className={`project-name-card${customName === opt.name ? ' selected' : ''}`}
                  >
                    <div className="project-name-card-title">{opt.name}</div>
                    <p className="project-name-card-rationale">{opt.rationale}</p>
                  </button>
                ))}
              </div>
            )}

            {!naming.loading && (
              <input
                className="input-field"
                type="text"
                placeholder="Or write your own"
                value={customName}
                onChange={(e) => setCustomName(e.target.value)}
              />
            )}

            <SubmitError error={naming.error} />

            <div className="dialog-actions">
              <PrimaryButton
                onClick={() => handleSave(customName.trim() || null)}
                disabled={naming.saving || !customName.trim()}
              >
                {naming.saving ? 'Saving…' : 'Name this Project'}
              </PrimaryButton>
              <LinkButton onClick={() => handleSave(null)} disabled={naming.saving}>
                Skip
              </LinkButton>
            </div>
          </div>
        </div>
      )}

      <div className="flow-container">
        <div className="scroll">

          <div className="section cover">
            <p className="eyebrow">Your Path</p>
            <h1>{chosen_candidate.name}</h1>
            <p className="cover-context-line">{prepared_for} · {identity_context}</p>
            {project_name && <p className="cover-context-line">{project_name}</p>}
            <p className="identity-thesis">{chosen_candidate.core_statement}</p>
            <p>{summary}</p>
          </div>

          <div className="section">
            <p className="eyebrow">WHAT THIS COULD BE</p>
            <p className="documentation">{WHAT_THIS_COULD_BE_EXPLANATION}</p>
            <div className="card"><p>{what_this_could_be}</p></div>
          </div>

          <div className="section">
            <p className="eyebrow">WHY IT FITS</p>
            <p className="documentation">{WHY_IT_FITS_EXPLANATION}</p>
            <div className="card">
              <h3>What You Can Do</h3>
              <p>{whyItFitsParagraphs[0]}</p>
            </div>
            {whyItFitsParagraphs[1] && (
              <div className="card">
                <h3>What You Want</h3>
                <p>{whyItFitsParagraphs[1]}</p>
              </div>
            )}
          </div>

          <div className="section">
            <p className="eyebrow">DAY IN LIFE</p>
            <p className="documentation">{DESTINATION_EXPLANATION}</p>
            <div className="card"><p>{life_it_leads_toward}</p></div>
          </div>

          <div className="section">
            <p className="eyebrow">HOW YOU GET THERE</p>
            <p className="documentation">{STRATEGY_EXPLANATION}</p>
            {strategic_decisions.map((sd, i) => (
              <ConstellationCard key={sd.decision} badge={i + 1} title={sd.decision}>
                <p style={{ padding: '14px 16px 0' }}>{sd.why_it_matters}</p>
                <p className="card-sub-label" style={{ margin: '14px 16px 6px' }}>OPEN DIRECTIONS</p>
                {sd.live_options.map((opt, j) => (
                  <div key={j}>
                    <p className="card-sub-label" style={{ margin: '0 16px 4px' }}>{opt.option}</p>
                    <p className="evidence-analysis" style={{ padding: '0 16px' }}>{opt.context}</p>
                  </div>
                ))}
              </ConstellationCard>
            ))}
          </div>

          <div className="section cta">
            <p className="eyebrow" style={{ textAlign: 'center' }}>WHAT&rsquo;S NEXT</p>
            <h2 style={{ textAlign: 'center' }}>Turn This Into a Project</h2>
            <div className="card cta">
              <p>{WHATS_NEXT_COPY}</p>
              {project_name ? (
                <>
                  <p>You&rsquo;re calling this <strong>{project_name}</strong>.</p>
                  <LinkButton onClick={handleOpenNaming}>Rename it</LinkButton>
                </>
              ) : (
                <LinkButton onClick={handleOpenNaming}>Name this project</LinkButton>
              )}
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
